[phases.setup]
nixPkgs = ["python311", "mysql-client"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python -m compileall ."]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
